### ISSUE TITLE
Rails 5.1 compatible release

### ISSUE THREAD

**Issue by maurosbu** [rails/activerecord-session_store#107]
Hi, is it possible to have a release compatible with rails 5.1?

Many thanks,
Mauro

**Comment by pandar1** [comment]
same request here

oracle enhanced 1.8.0 with rails 5.1.0 on jruby 9.1.8.0

Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    activerecord-oracle_enhanced-adapter java was resolved to 1.8.0, which depends on
      activerecord (~> 5.1.0.rc) java

    activerecord-session_store java was resolved to 1.0.0, which depends on
      activerecord (< 5.1, >= 4.0) java

    rails java was resolved to 5.1.0, which depends on
      activerecord (= 5.1.0) java

Could not find gem 'activerecord (< 5.1, >= 4.0) java', which is required by gem 'rails java', in any of the sources.


gem list follows


actioncable (5.1.0)
actionmailer (5.1.0)
actionpack (5.1.0)
actionview (5.1.0)
activejob (5.1.0)
activemodel (5.1.0)
activerecord (5.1.0)
activerecord-oracle_enhanced-adapter (1.8.0)
activerecord-session_store (1.0.0)
activesupport (5.1.0)
arel (8.0.0)
builder (3.2.3)
bundle (0.0.1)
bundler (1.14.6)
coffee-rails (4.2.1)
coffee-script (2.4.1)
coffee-script-source (1.12.2)
concurrent-ruby (1.0.5 java)
did_you_mean (default: 1.0.1)
erubi (1.6.0)
erubis (2.7.0)
execjs (2.7.0)
globalid (0.3.7)
i18n (0.8.1)
jar-dependencies (default: 0.3.10)
jquery-rails (4.3.1)
jruby-openssl (0.9.20 java)
jruby-readline (1.1.1 java)
json (1.8.3 java)
loofah (2.0.3)
looking_for (0.3.0)
mail (2.6.4)
method_source (0.8.2)
mime-types (3.1)
mime-types-data (3.2016.0521)
minitest (default: 5.4.1)
multi_json (1.12.1)
net-telnet (default: 0.1.1)
nio4r (2.0.0 java, 1.2.1 java)
nokogiri (1.7.1 java)
pdf-core (0.7.0)
power_assert (default: 0.2.3)
prawn (2.2.2)
prawn-table (0.2.2)
psych (2.2.4 java)
puma (3.8.2 java)
racc (1.4.14 java)
rack (2.0.1)
rack-test (0.6.3)
rails (5.1.0)
rails-dom-testing (2.0.2)
rails-html-sanitizer (1.0.3)
railties (5.1.0)
rake (default: 10.4.2)
rdoc (default: 4.2.0)
ruby-plsql (0.6.0)
sass (3.4.23)
sass-rails (5.0.6)
sprockets (3.7.1)
sprockets-rails (3.2.0)
test-unit (default: 3.1.1)
thor (0.19.4)
thread_safe (0.3.6 java)
tilt (2.0.7)
ttfunk (1.5.0)
tzinfo (1.2.3)
tzinfo-data (1.2017.2)
uglifier (3.1.12)
websocket-driver (0.6.5 java)
websocket-extensions (0.1.2)
will_paginate (3.1.5)

**Comment by rafaelfranca** [comment]
1.1.0 released https://github.com/rails/activerecord-session_store/releases/tag/v1.1.0
