### ISSUE TITLE
Sessions not working in Rails 5.1.0 when using the db

### ISSUE THREAD

**Issue by pandar1** [rails/activerecord-session_store#109]
Please check my rails issue #28698

Please tell me if I have to move that issue here... Thanks

**Comment by pandar1** [comment]
Please any one can investigate on this issue?

**Comment by rafaelfranca** [comment]
Hey @pandar1! While this open source project has maintainer they all have different things to do and this issue may be not high priority for them. So I recommend you to try to investigate the issue yourself and try to fix it since you already have the context and can reproduce easily.

**Comment by pandar1** [comment]
I have developed a minimal app that replicates the behaviour, if you want to try it it's here:
https://github.com/rails/rails/files/996254/bugapp.txt
I don't think I have the experience on the inner workings of rails to solve the problem myself...

**Comment by rafaelfranca** [comment]
Thanks! This app helps a lot

**Comment by pandar1** [comment]
I closed it because I have updated all the gems including rails and now my problem is gone...

**Comment by rafaelfranca** [comment]
Sounds good. Thanks for reporting back
