### ISSUE TITLE
Sessions for all the tenants is being stored in public schema in multi tenant Rails application

### ISSUE THREAD

**Issue by m-ramizraja** [rails/activerecord-session_store#110]
I am creating a multi tenant Rails application using apartment gem and Activerecord Session store. Tenants are being created like a charm but there is one issue, application is only storing sessions in Public schema's sessions table instead of storing it into tenant's schema's sessions table.

This is why whenever I try to send post request from tenant, it gives me **Invalid form authenticity token** error.

Post requests from main application are working fine.

How can I fix this?

PS: I am using postgresql database and Rails version is `4.2.5.2`

**Comment by bdewater** [comment]
You'll probably need to create your own multi-tenant aware session class that works with the apartment gem, see the "You may provide your own session class" part of the readme file.

**Comment by ashwintastic** [comment]
@bdewater please elaborate why do we need to do this ?
