### ISSUE TITLE
Default migration does not work on MySQL utf8mb4 tables

### ISSUE THREAD

**Issue by tkalliom** [rails/activerecord-session_store#114]
The generated migration adds a 255-character column and tries to add an index for it. If the character encoding for the database is set to `utf8mb4`, the modern recommendation, the index length becomes 1020 bytes, which is larger than the MySQL maximum index length of 767 bytes.

Would it be possible to e.g. use 191-character `session_id`s? 255 characters seems like an awful lot...

**Comment by rafaelfranca** [comment]
255 is the default column size for all string columns of Rails. If that don't fits your needs you can always change it, but we are not going to change the default.

This index problem with utf8mb4 encoding only exists in MySQL older than 5.7.
