### ISSUE TITLE
Skip session option doesn't work

### ISSUE THREAD

**Issue by AlfonsoUceda** [rails/activerecord-session_store#122]
Hi folks

I've upgraded a rails application from 3.2 to 5.1.4 and it is using this gem, the problem came when I updated to rails 5.X and I wanted to skip session in api controllers.

In my code, I have a `before_action` like this:
```ruby
request.session_options[:skip] = true
```
but even setting `skip: true` a session will be created in the database.

I've seen in rails 4 didn't happen because we used the legacy support session store class and rack < 2, but with the rails 5 upgrade, we are using rack > 2 and the new session store class.

Trying to find the session by its id and if it isn't found it saves the session, check this line: https://github.com/rails/activerecord-session_store/blob/master/lib/action_dispatch/session/active_record_store.rb#L128

Is there a way to avoid this behaviour?

Thanks!

**Comment by mkaczmarczyk** [comment]
@AlfonsoUceda I've created a monkey-patch to implement your fix to the `get_session_model`. And It's called but in the wrong order. First is always called the `get_session_model` and after that the `before_action` in my controller that contains 
`request.session_options[:skip] = true`. I've tried to place this in my SessionController (I'm using Device).

Basically, I'm trying to optimize my app, so bots that enter the login page do not create a session.

**Comment by manchester-kev** [comment]
Sorry to open this again but I've run into this issue using latest version of the library on Rails 5.2.8.. We have a couple of 'healthcheck' endpoints that are accessible without auth and are polled, and unfortunately each hit causes a new record to be written into the sessions table. 
I have tried setting request.session_options[:skip] to true, and whilst this prevents a session cookie from being sent, an empty session is still written into the sessions table.
Any ideas how others have worked around this would be very welcome.
Thanks.

**Comment by dolzenko** [comment]
I assume this happens because in find_session new session id should be generated, so we effectively have to reserve the ID by persisting to DB, still is there a way to opt out of this behavior?

**Comment by CR4567** [comment]
I was just struggling with the same behavior.
Did you try with 
request.session_options[:drop] = true 

I also had to made some adjustments in the login process, so that the session is not dropped during login.
