### ISSUE TITLE
Generated migration fails on Rails 5.1.4

### ISSUE THREAD

**Issue by dpneumo** [rails/activerecord-session_store#124]
Addendum: I see this has been addressed in PR 115 but does not appear to be in master yet.

Gemfile:
```
source 'https://rubygems.org'
gem 'rails', '~> 5.1.4'
gem 'activerecord-session_store'
...
```

Running: rails generate active_record:session_migration

```
20180205180207_add_sessions_table.rb:

class AddSessionsTable < ActiveRecord::Migration
  def change
    create_table :sessions do |t|
      t.string :session_id, :null => false
      t.text :data
     ...
```
Running:  rails db:migrate
```
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class AddSessionsTable < ActiveRecord::Migration[4.2]
.../db/migrate/20180205180207_add_sessions_table.rb:1:in `<top (required)>'
...
Caused by:
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class AddSessionsTable < ActiveRecord::Migration[4.2]
```

Workaround: Changing the migration first line to
```
class AddSessionsTable < ActiveRecord::Migration[5.0]
```

fixes the problem for me. However, the correct fix is in the migration template.

Change lib/generators/active_record/templates/migration.rb first line to:
```
class <%= migration_class_name %> < ActiveRecord::Migration[Rails.version]
```

**Comment by RaykPlatzek** [comment]
still not in master and same thing happening with Rails 5.2, so needed to add [5.2]

**Comment by saitho** [comment]
Should be in master now (https://github.com/rails/activerecord-session_store/pull/115).

**Comment by tom-brown** [comment]
error still persists in rails 5.2

**Comment by jasonfb** [comment]
I am seeing this on the latest version of this gem 1.1.1

 since this is core functionality to Rails, it seem the work-around, while easy, shouldn't really be considered good enough. can we re-open?
