### ISSUE TITLE
add user_id to model ?

### ISSUE THREAD

**Issue by c0ze** [rails/activerecord-session_store#127]
is it possible to add and save additional fields to the model ?

I modified the migration and added `user_id`.

I tried `session.model.user_id = user.id ` during login, but it seems `session` doesn't have model at this stage :

```
NoMethodError (undefined method `model=' for #<ActionDispatch::Request::Session:0x007fd69e6b76b0>):
```

what is the best approach for this ?

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
