### ISSUE TITLE
doesn't work with multi-tenant rails app 

### ISSUE THREAD

**Issue by ashwintastic** [rails/activerecord-session_store#133]
I have created multi-tenant rails app every thing is working fine for default database. but it gives **Can't verify CSRF token authenticity.** if i try to post from tenant

**Comment by rafaelfranca** [comment]
Probably because it is reading the session from the wrong database. This library indeed don't support multi-tenant rails app out of the box. Feel free to implemented if you want. Closing since we don't take feature requests in the issue tracker.

**Comment by Grandvizir** [comment]
Hi guys,

I am working on a multi-tenant rails app as well and by default active_session_store is reading the wrong schema of the database as @rafaelfranca explained. 
To avoid this: 
`ActiveRecord::SessionStore::Session.table_name = 'legacy_session_table'` where your table name should include your Database schema. `public.sessions` in my case.

Hope this will help you!
