### ISSUE TITLE
Missing important commit from December in latest release (.supports_migrations? removal)

### ISSUE THREAD

**Issue by saitho** [rails/activerecord-session_store#136]
Hi,

I'm using v1.1.1 which was released in March and am still getting the exception that .supports_migrations? does not exist. This check was removed in December (https://github.com/rails/activerecord-session_store/commit/01c632957f92020b6e1d30e4b5250e45e22a574c); the commit is somehow missing in the v1.1.1 release.

This commit is required for Rails 5.1 compatibility.

**Comment by rafaelfranca** [comment]
You can use the gem pointing to github. We will release it when it is ready.
