### ISSUE TITLE
uninitialized constant ActiveRecord::SessionStore::Session

### ISSUE THREAD

**Issue by jpickwell** [rails/activerecord-session_store#142]
After updating to v1.1.2, I now receive the error `uninitialized constant ActiveRecord::SessionStore::Session`. I've figured out that this is caused by the change to how the `active_record/session_store/session` file is required (inside an Active Support `on_load` block), and that I'm using an initializer file for setting options.

I feel like that change to how files were required is a breaking change and the version should have been bumped to v2.0.0.

**Comment by AirWick219** [comment]
Also seeing this same issue .. locking down to 1.1.1

**Comment by jpickwell** [comment]
@AirWick219, if you want to use the latest version of this gem, you could do something like the following in an initializer:
```ruby
# frozen_string_literal: true
# config/initializers/session_store.rb

Rails.application.config.session_store(:active_record_store)

ActiveSupport.on_load(:active_record) do
  ActiveRecord::SessionStore::Session.serializer = :json
end
```

But, I stand by my original assessment that there was a breaking change.

**Comment by sikachu** [comment]
@jpickwell sorry about that, it was not my intention to release a patch release with a breaking change. I did a scan though the commits log, saw #126, but really didn't think that it'd be a breaking change. 😓 

I'll take a look in the morning (JST) to see what we can do about this. Maybe we can signal Rails to autoload constant if you calls `ActiveRecord::SessionStore::Session`?

/cc @Edouard-chin @kaspth

**Comment by kaspth** [comment]
It's not meant to be a breaking change, so we should find a way to fix this. Ideas are welcome!

**Comment by Edouard-chin** [comment]
I also didn't think about it being a breaking change , sorry for that. Will try to figure out how we can solve this
