### ISSUE TITLE
Version bump?

### ISSUE THREAD

**Issue by mweitzel** [rails/activerecord-session_store#171]
Hello, could you please issue a `1.1.4` version? #159 was merged, but as a folks have mentioned in the comments a release would be well received, lovely, fantastic, celebrated by the masses, and all around a Good Time 😄.

**Comment by rafaelfranca** [comment]
Yes. Some day we will release this. For now, there is no need to wait to celebrate, you can use the master branch and celebrate right now.

**Comment by zofrex** [comment]
If I may ask, why "some day" and not "today"? :) Is there a release schedule for this gem, or is there a blocker for a release?
