### ISSUE TITLE
Rack 3 compatibility

### ISSUE THREAD

**Issue by alipman88** [rails/activerecord-session_store#198]
I'm using activerecord-session_store and I'd like to upgrade a Rails app from rack 2.x to 3.x.

However, activerecord-session_store does not yet support rack 3:

```
$ bundle install
Fetching gem metadata from https://gems.contribsys.com/..
Fetching gem metadata from http://rubygems.org/.......
Resolving dependencies.....................................................
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    rack (~> 3.0.2)

    activerecord-session_store was resolved to 2.0.0, which depends on
      rack (>= 2.0.8, < 3)
```

Are there plans to upgrade this gem to support rack 3? I'm scanning [rack's upgrade guide ](https://github.com/rack/rack/blob/main/UPGRADE-GUIDE.md) and no breaking changes jump out at me. (The only possibly-required action I'm seeing is adding `rack-session` as a dependency, which was removed from rack 3, but I don't believe this gem relies on `Rack::Session`.)

Happy to conduct a more thorough examination, but wanted to check in first whether someone else had already begun, or perhaps it's simply an oversight that the version hasn't yet gotten bumped.

**Comment by fayeroske** [comment]
+1, any updates on supporting rack 3?

**Comment by alaarab** [comment]
same issue here

**Comment by eszjay** [comment]
activerecord-session_store [depends on actionpack](https://github.com/rails/activerecord-session_store/blob/9198a952916df925f36ac2beab247296ee5c0341/activerecord-session_store.gemspec#L23) which is [currently restricted to rack ~> 2.0](https://github.com/rails/rails/blob/c15ee6e7b5065db3c46afa1f025b8e45f443604e/actionpack/actionpack.gemspec#L38)
[Rack 3 support is targeted at Rails 7.1.0](https://github.com/rails/rails/pull/46594)

**Comment by byroot** [comment]
Fixed in https://github.com/rails/activerecord-session_store/pull/206 (for Rails 7.1)
