### ISSUE TITLE
"Undefined method logger.silence"

### ISSUE THREAD

**Issue by slondr** [rails/activerecord-session_store#202]
I just installed the gem for the first time in a Rails 6.1 application, and the titular error is thrown whenever I call `session.delete`.

**Comment by slondr** [comment]
It seems that the error disappears if I unset the environment variable `RAILS_LOG_TO_STDOUT=1`

**Comment by Physium** [comment]
Just faced this issue and found out that was a massive discussing this issue [here](https://github.com/rails/activerecord-session_store/issues/176).

Seems like you are using a custom logger of sort? If so they have updated the instruction get your custom logger to `include ActiveSupport::LoggerSilence`

Reference: [https://github.com/rails/activerecord-session_store/pull/180/files](https://github.com/rails/activerecord-session_store/pull/180/files)

**Comment by byroot** [comment]
What @Physium said.
