### ISSUE TITLE
DEPRECATION WARNING: `#quietly` is deprecated in rails-4.2.0.beta4

### ISSUE THREAD

**Issue by AUS3RIS** [rails/activerecord-session_store#36]
Getting this while in 4.2.0.beta4.

```
DEPRECATION WARNING: `#quietly` is deprecated and will be removed in the next release.
(called from get_session at /Users/Austris/.rvm/gems/ruby-2.1.5@rails-pre/bundler/gems/activerecord-session_store-e879bf087eb6/lib/action_dispatch/session/active_record_store.rb:64)
```

**Comment by AUS3RIS** [comment]
@denisahearn thank you!

**Comment by srogers** [comment]
"quietly".  Too much irony there.  Thanks for the patch.

**Comment by dgm** [comment]
Is this gem unmaintained? I don't see any activity for 9 months...

**Comment by runwaldarshu** [comment]
It will be really nice to get this fixed.

**Comment by hasghari** [comment]
:+1:

**Comment by sikachu** [comment]
I'm going to release a new version after doing some housekeeping. You can track the status on #34.

**Comment by sikachu** [comment]
#34 has been merged in. Please look forward to 0.1.1 release.

**Comment by sikachu** [comment]
I've implemented the fix for both thread safety issue and `quietly` deprecation and pushed out a prelease gem. Would you mind testing out `0.1.1.pre` and report back if you still run into any issue?

Thanks!
