### ISSUE TITLE
Version 0.1.1 breaks Syslog::Logger setups

### ISSUE THREAD

**Issue by jmazzi** [rails/activerecord-session_store#42]
For those of us that use Syslog::Logger for our `config.logger` (config/environments/[env].rb) are having an issue with the latest update. Mainly, instances of Syslog::Logger do not respond to `silence`. However, they do respond to `quietly` method. Here is the error it creates:

```ruby
helix (webdev) > ActiveRecord::Base.logger.silence
ArgumentError: wrong number of arguments (0 for 1)
from /usr/local/lib/ruby/gems/2.0.0/gems/activesupport-4.1.9/lib/active_support/core_ext/kernel/reporting.rb:82:in `capture'
from (irb):3
from /usr/local/lib/ruby/gems/2.0.0/gems/railties-4.1.9/lib/rails/commands/console.rb:90:in `start'
from /usr/local/lib/ruby/gems/2.0.0/gems/railties-4.1.9/lib/rails/commands/console.rb:9:in `start'
from /usr/local/lib/ruby/gems/2.0.0/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:69:in `console'
from /usr/local/lib/ruby/gems/2.0.0/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
from /usr/local/lib/ruby/gems/2.0.0/gems/railties-4.1.9/lib/rails/commands.rb:17:in `<top (required)>'
from /home/helix/app/current/bin/rails:4:in `require'
from /home/helix/app/current/bin/rails:4:in `<main>'
helix (webdev) > ActiveRecord::Base.logger.class
=> Syslog::Logger
helix (webdev) > 
``` 

`logger` is set installer [here](https://github.com/rails/activerecord-session_store/blob/master/lib/action_dispatch/session/active_record_store.rb#L118-L120) which in our case is `ActiveRecord::Base.logger`.

**Comment by sikachu** [comment]
Thanks for reporting in. I'll try to implement the fix and release 0.1.2 as soon as possible.

Basically what happen was that I backported a proposed patch that implement method name `silence`. I forgot that it actually may causing issue if you're using it with Logger that doesn't ship with Ruby. I apologize.

**Comment by jmazzi** [comment]
@sikachu thanks, we appreciate it! :)

**Comment by jmazzi** [comment]
@sikachu do you have a release date in mind?

**Comment by sikachu** [comment]
I just got time to look into this. Sorry for kept you waiting.

It turns out that it's because we forgot to [include](https://github.com/rails/activerecord-session_store/blob/1cc0daf77d542045da4f6a43cba9ce04c27453dd/lib/active_record/session_store.rb#L37) `ActiveRecord::SessionStore::Extension::LoggerSilencer` to `Syslog::Logger`. I'll add the include and release a new version.

Oh, and it seems like you see the `quietly` and `silence` method there because they got monkeypatched to [`Kernel`](https://github.com/rails/rails/blob/v4.2.0/activesupport/lib/active_support/core_ext/kernel/reporting.rb#L114-L123). They are actually acting differently from what's defined in Logger as well. I think it's probably a good idea for me to rename the method to something else.

**Comment by sikachu** [comment]
@jmazzi would you mind trying `master` when you have a chance, before I release 0.1.2? Thanks!

**Comment by JustinJruby** [comment]
I also have this problem. 0.1.1 doesn't work for me for the reason above. 
With master, I'm getting undefined method `silence_logger' for #<Log4r::Logger:0x4764030>

**Comment by sikachu** [comment]
@JustinJruby if you add `Log4r::Logger.send :include, ActiveRecord::SessionStore::Extension::LoggerSilencer` into your initializer then pretty sure this will work.

... however, that feels hackish. I need to come up with dynamic way to include that module into the current logger. Maybe I could just do `ActiveRecord::Base.logger.send :include`

I need to investigate more on this. It sucks that we have to include this method in the logger that you're using, but it's better than leaking session data or monkeypatching `Kernel` like Active Support does.

**Comment by JustinJruby** [comment]
Thanks!

**Comment by jmazzi** [comment]
@sikachu master is working for us :+1:

**Comment by stevepm** [comment]
Had the same issue and master worked for us too.
