### ISSUE TITLE
uninitialized constant ActiveRecord::SessionStore in Rails 4.2.0 engine

### ISSUE THREAD

**Issue by emclab** [rails/activerecord-session_store#43]
We are upgrading a Rails 3.2 engine to Rails 4.2.0 on ruby 2.0.0. Gem 'activerecord-session_store' was added to engine's gemspec following gem's instruction:

  s.add_dependency 'activerecord-session_store' 

and added following in initializers/session_store.rb under dummy:

  Dummy::Application.config.session_store :active_record_store, :key => '_my_app_session'

then, we did bundle install. When we ran:

  bundle exec rails generate active_record:session_migration

There is the error from the gem's generator:

/activerecord-session_store-0.1.1/lib/generators/active_record/session_migration_generator.rb:16:in `session_table_name': uninitialized co
nstant ActiveRecord::SessionStore (NameError).

We moved the gem into engine's Gemfile and there is same error. Is this a compatibility issue or something we missed?

**Comment by emclab** [comment]
Under lib/../engine.rb, we have code pointing to session table:

    initializer "Authentify.add_middleware" do |app|
      ActiveRecord::SessionStore::Session.table_name = 'authentify_sessions'
      app.middleware.use ActiveRecord::SessionStore
    end

**Comment by emclab** [comment]
What we did is to add gem 'activerecord-session_store'  to engine's Gemfile besides to the .gemspec and the error disappeared.

**Comment by emclab** [comment]
Reopened the issue as the last try did not fix the problem.

**Comment by straydogstudio** [comment]
@emclab Was there any tangible resolution to this?

**Comment by jassiwins** [comment]
Getting the sam error while upgrading from Ruby 1.9.3 to Ruby 2.4.1
NameError: uninitialized constant ActiveRecord::SessionStore

Any solutions??
