### ISSUE TITLE
How could I silence the logs in rails server?

### ISSUE THREAD

**Issue by fluke** [rails/activerecord-session_store#44]
It's a bit hard to debug with SQL statements like these taking up most of the console.

```
SQL (1.9ms)  UPDATE "sessions" SET "data" = $1, "updated_at" = $2 WHERE "sessions"."id" = $3  [["data", "BAh7DkkiEXByZXZpb3VzX3VybAY6BkVGSSIVL215X3Byb2ZpbGUvZWRpdAY7\nAFRJIhhhcHBsaWNhbnRfcmV........
```

**Comment by sikachu** [comment]
* What version of the gem are you using?
* Are you overriding the value of your logger?
* Can you try the `master` version to see if it solves your issue?

**Comment by kartikluke** [comment]
Using version 0.1.1 at master.
`Using activerecord-session_store 0.1.1 from git://github.com/rails/activerecord-session_store.git (at master)`

I'm not overriding the value. Not that I know of.

**Comment by sikachu** [comment]
That's weird, because that's where I push the new patch for silencing the log in. Could you paste in the output of `ActiveRecord::Base.logger` and `ActiveRecord::Base.logger.respond_to?(:silence_logger)`?

I'd love to get this fix, because having this data printed out to the log is a security concern as well.

**Comment by kartikluke** [comment]
```
irb(main):015:0> ActiveRecord::Base.logger
=> #<ActiveSupport::Logger:0x007fb587cd6ab0 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x007fb587cd6a60 @datetime_format=nil>, @formatter=#<ActiveSupport::Logger::SimpleFormatter:0x007fb587bc9348 @datetime_format=nil>, @logdev=#<Logger::LogDevice:0x007fb587cd6a10 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<File:/Users/kartikluke/Documents/autoclave/log/development.log>, @mutex=#<Logger::LogDevice::LogDeviceMutex:0x007fb587cd69e8 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x007fb587cd6998>>>>

irb(main):016:0> ActiveRecord::Base.logger.respond_to?(:silence_logger)
=> false
```

**Comment by sikachu** [comment]
It seems like that the module didn't get included correctly, but in that case it should have raised an exception like in #42. I'm really not sure what's going on now ...

Would you mind gist me the log? Also, what happen if you add:

```
ActiveSupport::Logger.send :include, ActiveRecord::SessionStore::Extension::LoggerSilencer
```

to your initializer?

**Comment by bhaveshf-cuelogic** [comment]
@sikachu : We are using v0.1.2 and want to silence the logs. Can you please let us know in which initializer file the following line should be added ?

`MyLogger.send :include, ActiveRecord::SessionStore::Extension::LoggerSilencer
`

**Comment by sikachu** [comment]
@bhaveshf-cuelogic any initializer file. For example, just create a new `config/initializers/activerecord-session_store.rb` and put that line in there.

Let me know how it goes.

**Comment by bhaveshf-cuelogic** [comment]
@sikachu : nope, its not working :(

`ActiveRecord::Base.logger.respond_to?(:silence_logger)` returns `true`

Following is the ActiveRecord::Base.logger object
`<ActiveSupport::Logger:0x00000004e955d0
 @default_formatter=#<Logger::Formatter:0x00000004e95558 @datetime_format=nil>,
 @formatter=#<ActiveSupport::Logger::SimpleFormatter:0x00000005064f00 @datetime_format=nil>,
 @level=0,
 @logdev=
  #<Logger::LogDevice:0x00000004e95508
   @dev=#<File:/home/work/projects/my_app/log/development.log>,
   @filename=nil,
   @mutex=#<Logger::LogDevice::LogDeviceMutex:0x00000004e954e0 @mon_count=0, @mon_mutex=#<Mutex:0x00000004e95490>, @mon_owner=nil>,
   @shift_age=nil,
   @shift_size=nil>,
 @progname=nil>`

**Comment by rafaelGuerreiro** [comment]
I am on rails 5.0.0.1, and I'm facing the same issue. I included the initializer, but it did not work.
My output is the same as @bhaveshf-cuelogic.

Before adding the initializer, my output is:
```
ActiveRecord::Base.logger
 => #<ActiveSupport::Logger:0x007fc9ae0496e0 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x007fc9ae049640 @datetime_format=nil>, @formatter=#<ActiveSupport::Logger::SimpleFormatter:0x007fc9ace58238 @datetime_format=nil>, @logdev=#<Logger::LogDevice:0x007fc9ae0495f0 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<File:/Users/rguerreiro/Documents/Stratasphere/workspace/stratasphere/log/development.log>, @mutex=#<Logger::LogDevice::LogDeviceMutex:0x007fc9ae0495c8 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x007fc9ae049578>>>, @local_levels=#<Concurrent::Map:0x007fc9ae049500 entries=0 default_proc=nil>, @thread_hash_level_key=:"ThreadSafeLogger#70252092345200@level">
```

```
ActiveRecord::Base.logger.respond_to?(:silence_logger)
 => true 
```

So I don't think that the problem would be solved by adding the initializer code.
But I did it anyway, like this:
`ActiveSupport::Logger.send :include, ActiveRecord::SessionStore::Extension::LoggerSilencer`

The output was the same as before.
Any insights on how to solve this issue?

**Comment by andie-chernysh** [comment]
Guys, looks like I have the same problem. This issue is almost 2 years old!!! Any updates how that could be fixed? Any workarounds?

**Comment by tarmo** [comment]
Hi, this issue likely happens because when `silence_logger` gets called in a nested context the nested call will reset the logger level before the parent call has finished and thus anything that happens in that window after the nested call returned and the parent call hasn't will have no silencing applied.

The `silence_logger` method should be storing the previous `thread_level` and restoring that instead of always assigning `nil` to it: https://github.com/rails/activerecord-session_store/blob/master/lib/active_record/session_store/extension/logger_silencer.rb#L49

**Comment by forrestblount** [comment]
I was still seeing this issue on 1.1.3 - setting `secure: true` resolved the issue.

**Comment by breim** [comment]
@forrestblount where you set secure: true?

**Comment by byroot** [comment]
The silencer was removed in 2.0.0, and users are now expected to include `ActiveSupport::LoggerSilence`.
