### ISSUE TITLE
Destroy session without delete session row

### ISSUE THREAD

**Issue by phlegx** [rails/activerecord-session_store#46]
Hi!

I use devise gem and activerecord-session_store. I want to logout a user but without delete the session row that contains additional data, like ```return_to``` path (path to return after logout).

**Here my question on devise:** https://github.com/plataformatec/devise/issues/3593
**Here the question on stackoverflow:** http://stackoverflow.com/questions/30077584/using-devise-store-location-scope-return-to-with-activerecord-session-store

**Comment by rafaelfranca** [comment]
We don't take questions on the issue tracker. Thanks.
