### ISSUE TITLE
Error on all requests

### ISSUE THREAD

**Issue by jkuchta** [rails/activerecord-session_store#47]
I receive the following error on all requests. This is related to upgrading to rails 4.

ArgumentError (wrong number of arguments calling `capture` (0 for 1)):
  /home.rvm/gems/jruby-1.7.9/gems/activerecord-session_store-0.1.1/lib/action_dispatch/session/active_record_store.rb:65:in `get_session'
  /home.rvm/gems/jruby-1.7.9/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:266:in `load_session'
  /home.rvm/gems/jruby-1.7.9/gems/actionpack-4.0.13/lib/action_dispatch/middleware/session/abstract_store.rb:43:in `load_session'
  /home.rvm/gems/jruby-1.7.9/gems/actionpack-4.0.13/lib/action_dispatch/middleware/session/abstract_store.rb:51:in `stale_session_check!'
  /home.rvm/gems/jruby-1.7.9/gems/actionpack-4.0.13/lib/action_dispatch/middleware/session/abstract_store.rb:43:in `load_session'
  /home.rvm/gems/jruby-1.7.9/gems/actionpack-4.0.13/lib/action_dispatch/request/session.rb:168:in `load!'
  /home.rvm/gems/jruby-1.7.9/gems/actionpack-4.0.13/lib/action_dispatch/request/session.rb:160:in `load_for_read!'
  /home.rvm/gems/jruby-1.7.9/gems/actionpack-4.0.13/lib/action_dispatch/request/session.rb:86:in `[]'
  /home.rvm/gems/jruby-1.7.9/gems/warden-1.2.3/lib/warden/session_serializer.rb:30:in `fetch'
  /home.rvm/gems/jruby-1.7.9/gems/warden-1.2.3/lib/warden/proxy.rb:212:in `user'
  /home.rvm/gems/jruby-1.7.9/gems/warden-1.2.3/lib/warden/proxy.rb:318:in `_perform_authentication'
  /home.rvm/gems/jruby-1.7.9/gems/warden-1.2.3/lib/warden/proxy.rb:104:in `authenticate'
  /home.rvm/gems/jruby-1.7.9/gems/warden-1.2.3/lib/warden/proxy.rb:114:in `authenticate?'
  /home.rvm/gems/jruby-1.7.9/gems/devise-3.4.1/lib/devise/controllers/sign_in_out.rb:10:in `signed_in?'
  org/jruby/RubyEnumerable.java:1474:in `any?'

**Comment by stevepm** [comment]
Did you find a fix for this?

**Comment by jkuchta** [comment]
I realized this is an issue with log4ruby and not with activerecord-session_store

**Comment by NileshN** [comment]
Hi, What was the issue with log4ruby? I am facing same issue. However I am using log4j gem
