### ISSUE TITLE
Upgrading to 0.1.1 fails (ArgumentError)

### ISSUE THREAD

**Issue by ssteeg-mdsol** [rails/activerecord-session_store#54]
As part of https://github.com/rails/activerecord-session_store/issues/36, I have been trying to upgrade from activerecord-session_store 0.0.1 -> 0.1.1, but I am having issues. In particular, I'm seeing the following kind of errors:
```ruby
{ "message": "Backtrace: [\"/Users/ssteeg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/core_ext/kernel/reporting.rb:89:in `capture'\", 
\"/Users/ssteeg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-session_store-0.1.1/lib/action_dispatch/session/active_record_store.rb:65:in `get_session'\", \"/Users/ssteeg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:266:in `load_session'\", 
\"/Users/ssteeg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/session/abstract_store.rb:43:in `block in load_session'\", 
\"/Users/ssteeg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/session/abstract_store.rb:51:in `stale_session_check!'\", 
\"/Users/ssteeg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/session/abstract_store.rb:43:in `load_session'\", 
\"/Users/ssteeg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/request/session.rb:180:in `load!'\", 
\"/Users/ssteeg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/request/session.rb:172:in `load_for_read!'\", 
\"/Users/ssteeg/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/request/session.rb:89:in `[]'\", 
\"/Users/ssteeg/work/hercules/app/controllers/application_controller.rb:43:in `set_current_user'\",
...
{ "message": "The following uncaught exception occurred: #<ArgumentError: wrong number of arguments (0 for 1)>" }
```

The code referenced isn't doing anything strange, just something like:
```ruby
def set_current_user
  ...
  current_user.login = session[:cas_user]
  ...
end
```

Have you seen this kind of error before? Are there any gotcha's when upgrading to the latest version of this gem?

**Comment by ssteeg-mdsol** [comment]
@sikachu If you have some time, could you please take a look?

**Comment by sikachu** [comment]
I can look at this next Monday. Sorry for taking so long.

**Comment by ssteeg-mdsol** [comment]
Thanks @sikachu - whenever you get the chance :smile:

**Comment by ssteeg-mdsol** [comment]
Any updates on this one?

**Comment by sikachu** [comment]
I just looked into it. I think we _might_ have fixed it already, but never released 0.1.2.

Can you try pointing to `master` and try to see if your issue has been resolved?

**Comment by ssteeg-mdsol** [comment]
That fixed it! Thanks very much :100:  

For others, I pointed my gemfile to `master` (`gem 'activerecord-session_store', branch: 'master', git: 'git@github.com:rails/activerecord-session_store.git'`) and also created a new logger.rb file in my `/config/initializers/` folder containing `Log4r::Logger.send :include, ActiveRecord::SessionStore::Extension::LoggerSilencer` as per https://github.com/rails/activerecord-session_store/issues/42

Any idea when 0.1.2 will be released?

**Comment by sikachu** [comment]
@ssteeg-mdsol I need to fix an issue with it building against Rails `master`, then I can cut 0.1.2. I hope that I will have time to do this this Friday.

**Comment by sikachu** [comment]
I just pushed [v0.1.2](https://github.com/rails/activerecord-session_store/releases/tag/v0.1.2) release since it looks like there's going to be a lot of change making this to work with Rails 5 (and newer version of Rack).
