### ISSUE TITLE
Contribution guidelines have a broken link

### ISSUE THREAD

**Issue by jshirley** [rails/activerecord-session_store#58]
> Make a Pull Request
> 
> Go to https://github.com/contributor/activerecord-session_store and select your feature branch. Click the 'Pull Request' button and fill out the form. Pull requests are usually reviewed within a few days.

The link there doesn't work, and `contributor` is a GitHub account. I'm not actually sure what was at that page, but it sounds quite interesting :)

**Comment by sikachu** [comment]
I think the _contributor_ part supposed to mean your username. I didn't write that one personally, but I think that's what it is ... (so, say, go to your fork and to that particular branch).

How do you think we should improve it to make it less confusing?

**Comment by jshirley** [comment]
That makes sense, I was really excited that GitHub had an interface for managing your forks into projects and was a bit disappointed :(

Perhaps, "Go to your fork, at `https://github.com/$github_name/activerecord-session_store and select your feature branch." would clear it up?

**Comment by sikachu** [comment]
I updated the CONTRIBUTING.md with your suggestion. Thank you for your suggestion.
