### ISSUE TITLE
Deprecation on Thread.exclusive

### ISSUE THREAD

**Issue by yoda** [rails/activerecord-session_store#63]
Due to ruby 2.3.0

Deprecation warning on:
Thread.exclusive is deprecated, use Mutex
lib/active_record/session_store/session.rb:32:in `find_by_session_id'

From:
https://github.com/ruby/ruby/commit/2069c9e031fc968d6d3d0fe30a9316851e4d91d8

**Comment by QuentinFchx** [comment]
@sikachu, @guilleiguaran could you please advice on this one ? :smile:

**Comment by QuentinFchx** [comment]
Awesome :+1: 
Thank you for your time
