### ISSUE TITLE
Rails 5/rack 2 support

### ISSUE THREAD

**Issue by synth** [rails/activerecord-session_store#68]
I tried using activerecord-session_store with a fresh Rails 5 app today. Using the generator I hit:

    uninitialized constant Rack::Session::Abstract::ENV_SESSION_OPTIONS_KEY

I assume this is because Rails 5 now depends on rack (~> 2.x) and this is no longer the correct constant.

**Comment by synth** [comment]
changing Rack::Session::Abstract::ENV_SESSION_OPTIONS_KEY to Rack::RACK_SESSION seems like it might work.

**Comment by sikachu** [comment]
We've fixed the issue after merging in #66 but have yet release a new version as Rails 5 RC hasn't come out yet. Could you please try using `master` and report back if you still seeing the issue?

I'm going to close this for now.
