### ISSUE TITLE
devise 4.0.0.rc1 sign_in does not work with current master (rails 5.0.0.beta2 used)

### ISSUE THREAD

**Issue by zpetukhov** [rails/activerecord-session_store#70]
Hi!

I'm not sure actually it is activerecord-session_store issue or devise issue.
But sign_in function does not work with devise 4.0.0.rc1, rails 5.0.0.beta2 and activerecord-session_store master.

I did some investigations and have fix for that.
There is one line needs to be fixed.
File: lib/action_dispatch/session/active_record_store.rb
Function: get_session_model
Line: id = generate_sid
Change to: id ||= generate_sid

Steps to reproduce described issue:
1. Create new Rails app with rails 5.0.0.beta2
2. add these lines to Gemfile:
gem 'devise', '4.0.0.rc1'
gem 'activerecord-session_store', :git => 'https://github.com/rails/activerecord-session_store.git'
3. Run these commands:
bundle install
rails generate devise:install
rails generate devise user
rake db:migrate
4. Add to config/environments/development.rb
config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }
5. point root in routes to somewhere (devise will not start without it)
root to: "home#index"
6. Run this:
rails generate controller home
7. add to this controller:
def index
end
8. create views/home/index.html.erb
It can be empty file.
9. Add these lines to app/views/layouts/application.html.erb:
 < div style='color:red'><%= flash[:notice] %>< /div>
 < div style='color:red'><%= flash[:alert] %>< /div>
 < div style='color:green'><%if user_signed_in?%>signed-in<%else%>no_signed<% end%>< /div>
10. Change initializers/session_store.rb to this line:
Rails.application.config.session_store :active_record_store
11. Run:
rails generate active_record:session_migration
rake db:migrate
12. Run application and sign_up using this url:
/users/sign_up
13. Sign out (you can do it by clearing cookies)
14. Try to log_in. Dont use checkbox "remember me".
This step doesnt work. After form submitted, you will be redirected to / and not signed in.

If you skip step 10 then all will work.
Problem starts when using this: session_store :active_record_store

Then try to apply patch, that I described in the beginning.
Then log_in will work.

**Comment by mvastola** [comment]
@zpetukhov This regression seems to indeed exist, but the fix you are offering causes other integration tests to fail. Working on a proper fix right now.
