### ISSUE TITLE
"Thread.exclusive is deprecated, use Mutex" error

### ISSUE THREAD

**Issue by jasnow** [rails/activerecord-session_store#73]
When I use **rake** while using this gem, I get **Thread.exclusive is deprecated, use Mutex** error on this line:
```
.../.rvm/gems/ruby-2.3.0/gems/activerecord-session_store-0.1.2/lib/
active_record/session_store/session.rb:32:in `find_by_session_id'
```
followed by stacktrace.

**Comment by benoittgt** [comment]
Fixed by this commit : https://github.com/rails/activerecord-session_store/commit/82a7540dd8095cf09fe4dd4966df2cf2001e56cb 

You have to use master or wait for the next release. 😉

**Comment by jasnow** [comment]
Thanks
