### ISSUE TITLE
Release plan for 1.0.0?

### ISSUE THREAD

**Issue by djcp** [rails/activerecord-session_store#78]
Thanks for your work on this gem, @sikachu !  We're using it in [dce_lti](https://github.com/harvard-dce/dce_lti/) and https://github.com/harvard-dce/dce_lti/pull/14 looks to fix our gem for ruby 2.3.x via your `1.0.0-pre` release. Any thoughts on when 1.0.0 will get an official release?

**Comment by sikachu** [comment]
@djcp I think the plan is to release it right around Rails 5.0 RC, given that everything on Rails side will be frozen by then. That hopefully will happen _soon_.

**Comment by djcp** [comment]
Excellent! Thanks!

**Comment by connorshea** [comment]
@sikachu Rails 5.0.0.rc1 dropped today! :D

https://github.com/rails/rails/releases/tag/v5.0.0.rc1

**Comment by sikachu** [comment]
I just pushed 1.0.0. Please report back if you found any issue.

**Comment by connorshea** [comment]
Thanks!
