### ISSUE TITLE
Potential issue with silencer and LogstashLogger/Sidekiq?

### ISSUE THREAD

**Issue by DaveCollinsJr** [rails/activerecord-session_store#82]
Hello,
Using activerecord-session_store-1.0.0 with Rails 4.2.5, ruby 2.2.3p173, and sidekiq v4.1.1   We've recently updated this project from Rails 3.2 and this Rails 4 version has not yet been deployed to production.

We have noticed what appears to be almost daily hanging of **all** of our sidekiq processes.  When we investigate the logs, the commonality is that the last thing each hung process did was log something simple.  Looking at the backtrace we see this pattern:

``` ruby
2016-06-17T20:23:47.574Z 18071 TID-gqnfahehc WARN: Thread TID-gqnfqn8gc 
2016-06-17T20:23:47.574Z 18071 TID-gqnfahehc WARN: /opt/elasticbeanstalk/lib/ruby/lib/ruby/2.2.0/monitor.rb:185:in `lock'
/opt/elasticbeanstalk/lib/ruby/lib/ruby/2.2.0/monitor.rb:185:in `mon_enter'
/opt/elasticbeanstalk/lib/ruby/lib/ruby/2.2.0/monitor.rb:209:in `mon_synchronize'
/opt/elasticbeanstalk/lib/ruby/lib/ruby/2.2.0/logger.rb:595:in `write'
/opt/elasticbeanstalk/lib/ruby/lib/ruby/2.2.0/logger.rb:378:in `add'
/var/app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-session_store-1.0.0/lib/active_record/session_store/extension/logger_silencer.rb:38:in `add_with_threadsafety'
/opt/elasticbeanstalk/lib/ruby/lib/ruby/2.2.0/logger.rb:434:in `info'
/var/app/current/app/workers/parking_session_parking_picture.rb:33:in `process!'
```

Where the last thing our application did was a simple Rails.logger.info statement.  This is happening in many different classes, but they _always_ have this pattern as their _last_ actions:

``` ruby
2016-06-17T20:23:47.572Z 18071 TID-gqnfahehc WARN: Thread TID-gqngzan1k 
2016-06-17T20:23:47.572Z 18071 TID-gqnfahehc WARN: /opt/elasticbeanstalk/lib/ruby/lib/ruby/2.2.0/monitor.rb:185:in `lock'
/opt/elasticbeanstalk/lib/ruby/lib/ruby/2.2.0/monitor.rb:185:in `mon_enter'
/opt/elasticbeanstalk/lib/ruby/lib/ruby/2.2.0/monitor.rb:209:in `mon_synchronize'
/opt/elasticbeanstalk/lib/ruby/lib/ruby/2.2.0/logger.rb:595:in `write'
/opt/elasticbeanstalk/lib/ruby/lib/ruby/2.2.0/logger.rb:378:in `add'
/var/app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-session_store-1.0.0/lib/active_record/session_store/extension/logger_silencer.rb:38:in `add_with_threadsafety'
/opt/elasticbeanstalk/lib/ruby/lib/ruby/2.2.0/logger.rb:434:in `info'
```

To further complicate matters, we are using LogstashLogger.  I believe we have properly configured the silencer (LogStashLogger is a Module not a class):

```
  # Manually Including Silencer is required by ActiveRecord::SessionStore
  config.logger.extend ActiveRecord::SessionStore::Extension::LoggerSilencer
```

Any recommendations on further troubleshooting?  Not even sure this is an activerecord-session_store issue, but it seemed like a logical place to start.

**Comment by wkruszewski** [comment]
@DaveCollinsJr I found this on sidekiq group and it looks like you have found the cause?
https://groups.google.com/forum/#!topic/sidekiq/GOuLM9waWog

> OK it appears that not properly including/extending the ActiveRecord::SessionStore::Extension::LoggerSilencer was the issue.

**Comment by byroot** [comment]
The silencer was removed in 2.0.0, and users are now expected to include `ActiveSupport::LoggerSilence`.
