### ISSUE TITLE
There's no changelog

### ISSUE THREAD

**Issue by vemv** [rails/activerecord-session_store#85]
Hi there!

I currently have this gem locked at `'~> 0.1'` in my Gemfile.

I see the gem has transitioned to 1.0. Is it safe to update my dependency?

(as per semver, theoretically anything could have changed from 0.x to 1!)

Maintaining a changelog would greatly help.

Cheers - Victor

**Comment by rafaelfranca** [comment]
CHANGELOG is here https://github.com/rails/activerecord-session_store/releases

**Comment by vemv** [comment]
Whoopsie. Generally I expect a `CHANGELOG` file, but I'll keep an eye on the releases tab from now on too.

Thanks much!
