### ISSUE TITLE
Expired sessions remain in the database

### ISSUE THREAD

**Issue by iamdriz** [rails/activerecord-session_store#97]
When a session expires through inactivity or the user closes their browser, the sessions remain in the database. How can I make sure that expired sessions are always deleted without having to run a background job to keep cleaning it out.

**Comment by iamdriz** [comment]
I've added this to the Session model:
~~~
def self.sweep(time = 15.minutes)
    if time.is_a?(String)
      time = time.split.inject { |count, unit| count.to_i.send(unit) }
    end
    delete_all "updated_at < '#{time.ago.to_s(:db)}'"
end
~~~

And then in the controller method for listing sessions, I first call it:
~~~
def index
  Session.sweep
  @sessions = Session.order('created_at desc')
end
~~~

**Comment by mvz** [comment]
@iamdriz see the `db:sessions:trim` task and #89.

**Comment by rafaelfranca** [comment]
The supported wait to remove expired session is to use the `db:sessions:trim` taks

**Comment by eliotsykes** [comment]
For developers working in environments where running rake tasks on a schedule is not possible/desirable, you can borrow the code from the `db:sessions:trim` task. 

You should check what the latest code is but currently it is: 

```rb
    cutoff_period = (ENV['SESSION_DAYS_TRIM_THRESHOLD'] || 30).to_i.days.ago
    ActiveRecord::SessionStore::Session.
      where("updated_at < ?", cutoff_period).
      delete_all
```

https://github.com/rails/activerecord-session_store/blob/e97fa9f0d20fd932ecee6124b0b46d244d6f7ce6/lib/tasks/database.rake#L17-L20
